shops:
    close:
        material: BARRIER
        materialData: 0
    ranks:
        material: EMERALD
        materialData: 0

        alreadyBought:
            material: EMERALD_BLOCK
            materialData: 0

        notBuyable:
            material: BEDROCK
            materialData: 0

    converters:
        material: GOLD_INGOT
        materialData: 0

        amounts:
            10: 5
            100: 50
            200: 100
            1000: 500
            2000: 1000
        to:
            material: GOLD_INGOT
            materialData: 0
        from:
            material: IRON_INGOT
            materialData: 0